Menu branch
Dev-Corps/tanjore pull request #35
Opened 2021-09-07 23:37 UTC by Keethan03

2021-09-10 15:34 UTC, janacm requested changes
Hey, the code works but there are a few best practices and code-style issues that you should fix up before we merge this branch in. Make sure you have the VS Code extension "prettier" installed, lmk if you don't.

2021-09-10 15:34 UTC, janacm commented on src/components/home/Home.module.css
> +  padding-top: 200px
Hey avoid using `px`. Stick with `%`.

2021-09-10 15:34 UTC, janacm commented on src/components/menu/Menu.component.tsx
> +import img1 from './images/menu1.png';
Make sure variable names describe what is contained inside them

2021-09-10 15:34 UTC, janacm commented on src/components/menu/Menu.component.tsx
> +   style = {{
Avoid using inline styles - move all of these to `Menu.module.css` and add a class for each of these divs instead. Reference that class in your css file. This helps with maintainability and reusability

2021-09-10 15:34 UTC, janacm commented on src/components/menu/Menu.component.tsx
> +
Just have one space between elements, not 2-3 please :)

2021-09-10 15:34 UTC, janacm commented on src/components/menu/Menu.module.css
> +transform: scale(1.33);
Fix indentation here

2021-09-10 19:39 UTC, Keethan03 commented
Alright sounds good! And no I do not have the VS code extension "prettier"
installed.

On Fri, Sep 10, 2021 at 11:34 AM janac meena ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey, the code works but there are a few best practices and code-style
> issues that you should fix up before we merge this branch in. Make sure you
> have the VS Code extension "prettier" installed, lmk if you don't.
> ------------------------------
>
> In src/components/home/Home.module.css
> <https://github.com/Dev-Corps/tanjore/pull/35#discussion_r706276120>:
>
> > @@ -2,4 +2,7 @@
>    width: 100%;
>    font-size: large;
>    color: red;
> +}
> +.footer{
> +  padding-top: 200px
>
> Hey avoid using px. Stick with %.
> ------------------------------
>
> In src/components/menu/Menu.component.tsx
> <https://github.com/Dev-Corps/tanjore/pull/35#discussion_r706276649>:
>
> > @@ -1,11 +1,65 @@
> -import React from 'react';
> +import React from "react";
> +import img1 from './images/menu1.png';
>
> Make sure variable names describe what is contained inside them
> ------------------------------
>
> In src/components/menu/Menu.component.tsx
> <https://github.com/Dev-Corps/tanjore/pull/35#discussion_r706277977>:
>
> >    return (
> -    <div>
> -        You like snacks?Yes!
> -        <Footer/>
> +
> +  <body>
> +
> +  <img src = {header}
> +   style = {{
>
> Avoid using inline styles - move all of these to Menu.module.css and add
> a class for each of these divs instead. Reference that class in your css
> file. This helps with maintainability and reusability
> ------------------------------
>
> In src/components/menu/Menu.component.tsx
> <https://github.com/Dev-Corps/tanjore/pull/35#discussion_r706278303>:
>
> > +    >
> +
> +  <div
> +    style = {{
> +    width: "600px",
> +    height: "475px",
> +    padding: "130px 50px 0px 115px",
> +  position: "relative"}}
> +
> +    >
> +
> +    <a href = {img2}><img src = {img2} className = {style.image2}/></a>
> +
> +  </div>
> +
> +
>
> Just have one space between elements, not 2-3 please :)
> ------------------------------
>
> In src/components/menu/Menu.module.css
> <https://github.com/Dev-Corps/tanjore/pull/35#discussion_r706278610>:
>
> > +.image1{
> +    width: 600px;
> +    height:475px;
> +  padding: "100px 0px 0px 165px";
> +
> +}
> +.image2{
> +    width: 600px;
> +    height: 475px;
> +    padding: "100px 50px 0px 105px";
> +
> +}
> +
> +.image1:hover{
> +
> +transform: scale(1.33);
>
> Fix indentation here
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dev-Corps/tanjore/pull/35#pullrequestreview-751538972>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP3J4HXWUPZOHFHLS4NN3TLUBIQRDANCNFSM5DTMOCEQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-25 23:51 UTC, TheVedhaGuy approved these changes

2021-09-25 23:52 UTC, merged